package com.novadart.novabill.shared.client.exception;

public enum AuthorizationError {
	
	NUMBER_OF_CLIENTS_QUOTA_REACHED,
	NUMBER_OF_INVOICES_QUOTA_REACHED,
	NUMBER_OF_ESTIMATIONS_QUOTA_REACHED,
	NUMBER_OF_CREDIT_NOTES_QUOTA_REACHED,
	NUMBER_OF_TRANSPORT_DOCUMENTS_QUOTA_REACHED,
	NOT_PREMIUM_USER,
	NUMBER_OF_COMMODITIES_QUOTA_REACHED,
	NUMBER_OF_PAYMENTTYPES_QUOTA_REACHED

}
