// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.novadart.novabill.domain;

import com.novadart.novabill.domain.Invoice;
import javax.persistence.Entity;

privileged aspect Invoice_Roo_Jpa_Entity {
    
    declare @type: Invoice: @Entity;
    
}
