package com.novadart.novabill.shared.client.dto;

public enum NotificationType {
	PREMIUM_UPGRADE, PREMIUM_EXTENSION, PREMIUM_DOWNGRADE, INVOICE_DOWNLOADED, PREMIUM_DOWNGRADE_30_DAYS, PREMIUM_DOWNGRADE_15_DAYS, PREMIUM_DOWNGRADE_7_DAYS
}